{% set name = "kmc_smudge_pairs" %}
{% set version = "3.1.2rc4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/gkanogiannis/KMC/archive/v{{ version }}.tar.gz
  sha256: 43ae55aabc1334a038e5898b2fdc9a1d254d6a434c9ad34e56663be1aec9dc42

build:
  skip: true  # [not linux]
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - make
  host:
    - zlib
    - bzip2

test:
  commands:
    - kmc --help

about:
  home: https://github.com/gkanogiannis/KMC
  summary: 'Fast and frugal disk based k-mer counter. Includes smudge_pairs.'
  license: GPL-3.0-or-later
  license_file: 
    - LICENSE.txt
    - vendor-licenses/

extra:
  recipe-maintainers:
    - gkanogiannis
